### ISSUE TITLE
9.1.0打开秒闪退

### ISSUE THREAD

**Issue by Aik-R** [Nekozuka-Hibiki/QQ-SyRadiant#12]
安卓15(2024-11-1) 澎湃os 2.0.10.0
提示“QQ使用的加固技术还没有适配当前安卓系统版本。”
java.lang.RuntimeException: Unable to instantiate application com.tencent.common.app.QFixApplicationImpl package com.tencent.mobileqq: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~sW0me88ZFkDc88_NryRPuA==/com.tencent.mobileqq-QGoxjKxVG0xCvIPAvKloeg==/base.apk"],nativeLibraryDirectories=[/data/app/~~sW0me88ZFkDc88_NryRPuA==/com.tencent.mobileqq-QGoxjKxVG0xCvIPAvKloeg==/lib/arm64, /data/app/~~sW0me88ZFkDc88_NryRPuA==/com.tencent.mobileqq-QGoxjKxVG0xCvIPAvKloeg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1541)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8240)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2661)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~sW0me88ZFkDc88_NryRPuA==/com.tencent.mobileqq-QGoxjKxVG0xCvIPAvKloeg==/base.apk"],nativeLibraryDirectories=[/data/app/~~sW0me88ZFkDc88_NryRPuA==/com.tencent.mobileqq-QGoxjKxVG0xCvIPAvKloeg==/lib/arm64, /data/app/~~sW0me88ZFkDc88_NryRPuA==/com.tencent.mobileqq-QGoxjKxVG0xCvIPAvKloeg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1356)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1534)
	... 11 more
大佬看看能解决吗

**Comment by Nekozuka-Hibiki** [comment]
@Aik-R 在玩 TIM，这个可能是框架不兼容 A15，有能力可自行换用 JM 的 LSP 打包试试看喵

**Comment by Aik-R** [comment]
虽然不是很懂，但我从某安到TG一直在用您的精简，十分感谢大佬的分享~ (可惜TIM没有频道

**Comment by Nekozuka-Hibiki** [comment]
@Aik-R 我回头有空再把新的 QQ 发上去吧

**Comment by Aik-R** [comment]
赞美大佬(๑′ᴗ‵๑)Ｉ Lᵒᵛᵉᵧₒᵤ❤
